#!/usr/bin/env python3
"""
Scan all SUBJECTXXX directories in UCLA_human_dataset and compute:
  - REST  AUC + peak C
  - STRESS AUC + peak C
  - AUC ratio (rest/stress) ≈ predicted CFR from AIF alone (assumes similar
    per-voxel tissue enhancement; actual CFR also depends on tree-state arrival)
  - Effective predicted CFR ≈ (AUC_rest / AUC_stress)  — first-order approximation

Why this matters: with our pipeline, CFR is bounded by the AUC ratio when
arrival/dispersion is similar between states. To target clinical CFR ≈ 3,
we look for patients with AUC_rest / AUC_stress ≈ 3.
"""
import os
import sys
import glob
import numpy as np
import scipy.io as sio

ROOT = "/home/molloi-lab/smb_mount/shared_drive/Hamid/UCLA_human_dataset"
HU_PER_MG_ML = 35.0   # 100 kVp default
BASELINE_N = 5


def load_aif(aif_path, time_path):
    aif = sio.loadmat(aif_path)["aif_vec"].ravel().astype(np.float64)
    t   = sio.loadmat(time_path)["time_vec"].ravel().astype(np.float64)
    if len(aif) != len(t):
        return None
    return t, aif


def drop_outlier(t, hu):
    if len(t) < 4:
        return t, hu, False
    dt = np.diff(t)
    typical = float(np.median(dt[:-1]))
    if dt[-1] > 3.0 * typical:
        return t[:-1], hu[:-1], True
    return t, hu, False


def process_aif(t, hu_raw, hu_per_mgml=HU_PER_MG_ML, baseline_n=BASELINE_N):
    """Returns (t_processed, c_mg_per_ml, baseline_hu, dropped_outlier, auc)."""
    t, hu, dropped = drop_outlier(t, hu_raw)
    baseline = float(np.mean(hu[:baseline_n]))
    delta = hu - baseline
    c = np.clip(delta, 0.0, None) / hu_per_mgml
    trapz_fn = getattr(np, "trapezoid", np.trapz)
    auc = float(trapz_fn(c, t))
    return t, c, baseline, dropped, auc


def scan_subject(subject_dir):
    """Return dict with AIF stats, or None if data is missing."""
    name = os.path.basename(subject_dir)
    rest_dir = os.path.join(subject_dir, "BOLUS_TRACKING_REST")
    stress_dir = os.path.join(subject_dir, "BOLUS_TRACKING_STRESS")
    info = {"subject": name}

    for state, d in (("rest", rest_dir), ("stress", stress_dir)):
        aif_p  = os.path.join(d, "AIF_autoGenerated.mat")
        time_p = os.path.join(d, "TIME_autoGenerated.mat")
        if not (os.path.isfile(aif_p) and os.path.isfile(time_p)):
            info[f"{state}_status"] = "MISSING"
            continue
        try:
            t, hu = load_aif(aif_p, time_p)
            tp, c, baseline, dropped, auc = process_aif(t, hu)
            info[f"{state}_status"]   = "OK"
            info[f"{state}_n"]        = len(tp)
            info[f"{state}_t_max"]    = float(tp[-1])
            info[f"{state}_baseline"] = baseline
            info[f"{state}_peak_HU"]  = float(hu.max())
            info[f"{state}_peak_dHU"] = float((hu - baseline).max())
            info[f"{state}_peak_C"]   = float(c.max())
            info[f"{state}_AUC"]      = auc  # mg·s/mL
            info[f"{state}_dropped"]  = dropped
        except Exception as e:
            info[f"{state}_status"] = f"ERR: {e}"
    return info


def main():
    subjects = sorted(glob.glob(os.path.join(ROOT, "SUBJECT*")))
    print(f"Found {len(subjects)} subjects under {ROOT}")
    print()

    rows = []
    for sd in subjects:
        info = scan_subject(sd)
        rows.append(info)

    # Print header
    hdr = (f"{'Subject':<22} {'REST AUC':>10} {'STR AUC':>10} {'ratio':>7} "
           f"{'REST peakC':>11} {'STR peakC':>11} "
           f"{'REST baseHU':>12} {'STR baseHU':>12}  Status")
    print(hdr)
    print("-" * len(hdr))

    ratios = []
    for r in rows:
        s = r["subject"]
        rest_status = r.get("rest_status", "?")
        stress_status = r.get("stress_status", "?")
        if rest_status == "OK" and stress_status == "OK":
            au_r = r["rest_AUC"]; au_s = r["stress_AUC"]
            ratio = au_r / au_s if au_s > 0 else float("inf")
            pk_r  = r["rest_peak_C"]; pk_s = r["stress_peak_C"]
            bl_r  = r["rest_baseline"]; bl_s = r["stress_baseline"]
            print(f"{s:<22} {au_r:>10.2f} {au_s:>10.2f} {ratio:>7.2f} "
                  f"{pk_r:>11.3f} {pk_s:>11.3f} "
                  f"{bl_r:>12.1f} {bl_s:>12.1f}  OK")
            ratios.append((s, ratio, au_r, au_s, pk_r, pk_s))
        else:
            print(f"{s:<22} {'-':>10} {'-':>10} {'-':>7} "
                  f"{'-':>11} {'-':>11} {'-':>12} {'-':>12}  "
                  f"REST={rest_status} STRESS={stress_status}")

    # Rank by ratio closeness to 3
    print()
    print(f"{'='*78}")
    print(f"Ranked by AUC ratio (closeness to clinical CFR target ≈ 3.0):")
    print(f"{'='*78}")
    ratios_sorted = sorted(ratios, key=lambda x: abs(x[1] - 3.0))
    for s, ratio, au_r, au_s, pk_r, pk_s in ratios_sorted:
        marker = " ⭐" if abs(ratio - 3.0) < 0.5 else ""
        print(f"  {s:<22} AUC_ratio = {ratio:.2f}  "
              f"(REST {au_r:.1f} / STRESS {au_s:.1f} mg·s/mL){marker}")

    # Also high-ratio candidates (CFR > 2 expected)
    print()
    print(f"{'='*78}")
    print(f"Patients with ratio > 2.0 (likely to give meaningful CFR in our pipeline):")
    print(f"{'='*78}")
    high = [r for r in ratios_sorted if r[1] > 2.0]
    if high:
        for s, ratio, au_r, au_s, pk_r, pk_s in sorted(high, key=lambda x: -x[1]):
            print(f"  {s:<22} ratio = {ratio:.2f}   "
                  f"REST_peak = {pk_r:.2f}, STRESS_peak = {pk_s:.2f} mg/mL")
    else:
        print("  none with ratio > 2 — all patients have AIF AUC similar across states")


if __name__ == "__main__":
    main()
