#!/usr/bin/env python3
"""
Step 0: prepare real patient AIF curve for downstream simulation.

Reads a MATLAB-format AIF (UCLA dataset convention):
    BOLUS_TRACKING_REST/AIF_autoGenerated.mat   -> var `aif_vec`  shape (N, 1), HU
    BOLUS_TRACKING_REST/TIME_autoGenerated.mat  -> var `time_vec` shape (N, 1), seconds

Outputs `aif_curve.csv` with columns `time_s, C_mg_per_mL` (baseline-subtracted,
converted to mg iodine / mL blood) ready for step3 voxelize and step4 perfusion.

Preprocessing (with rationale):
  1. Drop trailing outlier (last point typically jumps to a much later time
     — single-shot AIF measured from the CTA scan, not the bolus tracking).
  2. Subtract baseline = mean of first 5 frames (pre-contrast aorta HU).
  3. Convert ΔHU -> mg/mL via HU_PER_MG_ML  (default 35 for 100 kVp single-energy CT).
  4. Clamp negative ΔHU to 0.

Usage:
    python3 scripts/step0_prepare_aif.py  AIF_MAT  TIME_MAT  OUT_CSV
                                          [--hu-per-mgml 35.0]
                                          [--baseline-n 5]
"""
import argparse
import os
import sys

import numpy as np
import scipy.io as sio


def load_aif_mat(aif_path: str, time_path: str):
    aif = sio.loadmat(aif_path)
    tme = sio.loadmat(time_path)
    aif_vec = aif["aif_vec"].ravel().astype(np.float64)
    time_vec = tme["time_vec"].ravel().astype(np.float64)
    if aif_vec.shape != time_vec.shape:
        raise ValueError(f"shape mismatch: aif {aif_vec.shape} vs time {time_vec.shape}")
    return time_vec, aif_vec


def drop_trailing_outlier(t: np.ndarray, hu: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Remove the last sample if its time gap is much larger than the median gap
    (clear signature of a single-shot measurement appended to a bolus-tracking series)."""
    if len(t) < 4:
        return t, hu
    dt = np.diff(t)
    typical = float(np.median(dt[:-1]))
    last_dt = float(dt[-1])
    if last_dt > 3.0 * typical:
        print(f"  dropping trailing outlier: t={t[-1]:.3f}s (gap {last_dt:.2f}s vs median {typical:.3f}s)")
        return t[:-1], hu[:-1]
    return t, hu


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("aif_mat", help="path to AIF_autoGenerated.mat")
    ap.add_argument("time_mat", help="path to TIME_autoGenerated.mat")
    ap.add_argument("out_csv", help="output CSV path (time_s, C_mg_per_mL)")
    ap.add_argument("--hu-per-mgml", type=float, default=35.0,
                    help="HU per (mg/mL) iodine; 35 ≈ 100 kVp single-energy. Use 25 for 120 kVp.")
    ap.add_argument("--baseline-n", type=int, default=5,
                    help="number of leading frames averaged for the pre-contrast HU baseline")
    args = ap.parse_args()

    for p in (args.aif_mat, args.time_mat):
        if not os.path.isfile(p):
            print(f"ERROR: missing file: {p}", file=sys.stderr)
            sys.exit(1)

    print(f"[step0] AIF mat   = {args.aif_mat}")
    print(f"[step0] TIME mat  = {args.time_mat}")
    print(f"[step0] hu_per_mgml = {args.hu_per_mgml}")
    print(f"[step0] baseline_n = {args.baseline_n}")

    t, hu_raw = load_aif_mat(args.aif_mat, args.time_mat)
    print(f"[step0] loaded {len(t)} points; t range [{t.min():.3f}, {t.max():.3f}] s; "
          f"HU range [{hu_raw.min():.2f}, {hu_raw.max():.2f}]")

    t, hu_raw = drop_trailing_outlier(t, hu_raw)

    baseline = float(np.mean(hu_raw[: args.baseline_n]))
    delta_hu = hu_raw - baseline
    c_mg_per_ml = np.clip(delta_hu, 0.0, None) / args.hu_per_mgml

    # np.trapezoid was added in numpy 2.x; fall back to np.trapz on older versions.
    trapz_fn = getattr(np, "trapezoid", np.trapz)
    auc = float(trapz_fn(c_mg_per_ml, t))  # mg·s/mL
    auc_hu_s = auc * args.hu_per_mgml
    peak_idx = int(np.argmax(c_mg_per_ml))

    print(f"[step0] after preprocessing: {len(t)} samples, t range [{t.min():.3f}, {t.max():.3f}] s")
    print(f"[step0]   baseline HU = {baseline:.2f}")
    print(f"[step0]   ΔHU range  [{delta_hu.min():.2f}, {delta_hu.max():.2f}]")
    print(f"[step0]   C range    [{c_mg_per_ml.min():.4f}, {c_mg_per_ml.max():.4f}] mg/mL")
    print(f"[step0]   AUC (full curve)        = {auc:.4f} mg·s/mL = {auc_hu_s:.2f} HU·s")
    print(f"[step0]   peak at t = {t[peak_idx]:.3f}s  ΔHU = {delta_hu[peak_idx]:.2f}  "
          f"C = {c_mg_per_ml[peak_idx]:.4f} mg/mL")

    os.makedirs(os.path.dirname(args.out_csv) or ".", exist_ok=True)
    with open(args.out_csv, "w") as f:
        f.write("# Real patient AIF (baseline-subtracted, HU -> mg/mL @ "
                f"{args.hu_per_mgml} HU per mg/mL)\n")
        f.write(f"# baseline_HU = {baseline:.4f} (mean of first {args.baseline_n} frames)\n")
        f.write(f"# source_aif  = {args.aif_mat}\n")
        f.write(f"# source_time = {args.time_mat}\n")
        f.write(f"# auc_mg_s_per_ml = {auc:.6f}\n")
        f.write(f"# peak_time_s    = {t[peak_idx]:.4f}\n")
        f.write(f"# peak_C_mg_per_ml = {c_mg_per_ml[peak_idx]:.6f}\n")
        f.write("time_s,C_mg_per_mL\n")
        for ti, ci in zip(t, c_mg_per_ml):
            f.write(f"{ti:.6f},{ci:.6f}\n")
    print(f"[step0] wrote {args.out_csv}")


if __name__ == "__main__":
    main()
